[build-system]
requires = [
    "setuptools",
    "setuptools_scm[toml]",
    "setuptools_scm_git_archive",
    "wheel",
]
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
root = "./"
# use current tag and not next one
version_scheme = "post-release"
